CREATE TABLE `users` (
	`num` INT NOT NULL AUTO_INCREMENT,
	`id` VARCHAR(30) NOT NULL,
	`password` VARCHAR(255) NOT NULL,
	`email` VARCHAR(100) NOT NULL,
	`name` VARCHAR(20) NOT NULL,
	`phone` VARCHAR(15) NOT NULL,
	`gender` VARCHAR(10) NOT NULL,
	`login_token` VARCHAR(255) NULL DEFAULT NULL,
	`role` INT NOT NULL DEFAULT '0',
	PRIMARY KEY (`num`)
)
COLLATE='utf8mb3_general_ci'
ENGINE=InnoDB
;
